---
# This role will add CNI to the cluster

- name: Copy the cni on master
  copy:
    src: "{{ role_path }}/files/calico.yaml"
    dest: /home/vagrant/calico.yaml
    mode: 0664

- name: Deploy calio
  become: True
  become_user: vagrant
  shell: kubectl apply -f /home/vagrant/calico.yaml